#ifndef PMATRIX_MAX_DIMENSIONS
#define PMATRIX_MAX_DIMENSIONS	(16)
#endif

#ifndef MAX_ORDER
#define MAX_ORDER	PMATRIX_MAX_DIMENSIONS
#endif

#ifndef MAX_LABELS
#define MAX_LABELS		(32)
#endif

#ifndef MAX_MATRIX_ELEMENTS
#define MAX_MATRIX_ELEMENTS	(16)
#endif

#ifndef MAX_DENOMINATORS
#define MAX_DENOMINATORS	(16)
#endif

#ifndef MAX_NUMERATORS
#define MAX_NUMERATORS	(16)
#endif

#ifndef MAX_EXCITATION_LEVEL
#define MAX_EXCITATION_LEVEL (16)
#endif
